apiVersion: v1
kind: Pod
spec:
  containers:
  - name: busybox
    image: busybox
    command:
    - sleep
    args:
    - 99d
  - name: alpine
    image: alpine
    command:
    - sleep
    args:
    - 99d
